version: 3
endpoint: http://121.229.113.196:19211
admin_secret: ${HASURA_GRAPHQL_ADMIN_SECRET}
metadata_directory: metadata
migrations_directory: migrations
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
